apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: quakewatch-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: quakewatch-alerts
    interval: 30s
    rules:
    - alert: QuakeWatchHighCPU
      expr: sum(rate(container_cpu_usage_seconds_total{namespace="quakewatch-helm",pod=~"quakewatch.*"}[5m])) by (pod) > 0.8
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "QuakeWatch pod {{ $labels.pod }} high CPU usage"
        description: "CPU usage is above 80% for 2 minutes"
    
    - alert: QuakeWatchPodDown
      expr: sum(kube_pod_status_phase{namespace="quakewatch-helm",pod=~"quakewatch.*",phase=~"Pending|Unknown|Failed"}) > 0
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "QuakeWatch pod is down"
        description: "Pod has been in non-running state for 30 seconds"
