apiVersion: v1
kind: Service
metadata:
  name: quakewatch
  namespace: {{ .Release.Namespace }}
  labels:
    app: quakewatch
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: quakewatch
